project:
  type: website
  output-dir: ../docs
  resources:
    - "hymn_tune_data.xlsx"

website:
  title: "ðŸŽµ Hymnary Organâ€“Hymnal Crossover"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hymns.qmd
        text: Hymnâ€“Tune Index
      - href: about.qmd
        text: About & Attribution

format:
  html:
    theme: styles.scss
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
